theme: jekyll-theme-hacker
title: Daniela's projects
subtitle: About me and my professional development
description: About me and my professional development. A technical space where I am interested in Python and web design.
